# Generated by Django 5.1 on 2024-09-01 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'tipousuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=150)),
                ('Telefono', models.IntegerField(null=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=150)),
                ('TipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.tipo_usuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
