# Generated by Django 5.1 on 2024-09-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0002_usuario_superusuario_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Apellidos',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
