# Generated by Django 5.1 on 2024-09-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0004_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Tipo_usuario',
        ),
    ]
