# Generated by Django 5.1 on 2024-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0005_remove_usuario_tipousuario_delete_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
    ]
