# Generated by Django 5.1 on 2024-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0006_usuario_usuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='programa',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'programa',
            },
        ),
    ]
