# Generated by Django 5.1 on 2024-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0007_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea_estrategica',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=150)),
                ('Secretario_Responsable', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'linea_estrategica',
            },
        ),
        migrations.CreateModel(
            name='Pilar_sectorial',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pilar_sectorial',
            },
        ),
    ]
