# Generated by Django 5.1 on 2024-09-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0008_linea_estrategica_pilar_sectorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaProducto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Valor_Medición', models.CharField(max_length=45)),
                ('Fecha_Inicio', models.DateField(verbose_name='Fecha inicio')),
                ('Fecha_Fin', models.DateField(verbose_name='Fecha limite')),
            ],
            options={
                'db_table': 'meta_producto',
            },
        ),
        migrations.CreateModel(
            name='Indicador_Producto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Unidad_Medida', models.CharField(max_length=50)),
                ('Linea_Base', models.IntegerField(null=True)),
                ('Linea_META', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.metaproducto')),
            ],
            options={
                'db_table': 'indicador_producto',
            },
        ),
    ]
