# Generated by Django 5.1 on 2024-09-08 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0009_metaproducto_indicador_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_producto',
            },
        ),
        migrations.CreateModel(
            name='PrioridadProducto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'prioridad_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=200)),
                ('Descripción', models.TextField()),
                ('Medición', models.CharField(max_length=150)),
                ('Progreso', models.FloatField()),
                ('ID_Indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.indicador_producto')),
                ('ID_LineaEstrategica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.linea_estrategica')),
                ('ID_Pilar_Sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.pilar_sectorial')),
                ('ID_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.estadoproducto')),
                ('ID_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.programa')),
                ('ID_usuarioAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AsignadoProducto', to=settings.AUTH_USER_MODEL)),
                ('ID_usuarioPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AsignarProducto', to=settings.AUTH_USER_MODEL)),
                ('Prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.prioridadproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='HistoricoProducto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField()),
                ('Descripción', models.TextField()),
                ('Soporte', models.FileField(upload_to='archivos/')),
                ('ID_estadoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.estadoproducto')),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ID_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.producto')),
            ],
            options={
                'db_table': 'historico_producto',
            },
        ),
    ]
