# Generated by Django 5.1 on 2024-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0015_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='Cod_programa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='Nombre',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
