# Generated by Django 5.1 on 2024-09-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0016_programa_cod_programa_alter_programa_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='ID',
        ),
        migrations.AddField(
            model_name='programa',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
