# Generated by Django 5.1 on 2024-09-15 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0017_remove_programa_id_programa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea_estrategica',
            name='Cod_LineaEstrategica',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilar_sectorial',
            name='Linea_estrategica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.linea_estrategica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='pilar_Sectorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.pilar_sectorial'),
            preserve_default=False,
        ),
    ]
