# Generated by Django 5.1 on 2024-09-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0018_linea_estrategica_cod_lineaestrategica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador_producto',
            name='Linea_META',
        ),
        migrations.RemoveField(
            model_name='indicador_producto',
            name='Linea_Base',
        ),
        migrations.RemoveField(
            model_name='indicador_producto',
            name='Unidad_Medida',
        ),
        migrations.RemoveField(
            model_name='pilar_sectorial',
            name='Linea_estrategica',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='pilar_Sectorial',
        ),
        migrations.AddField(
            model_name='producto',
            name='Linea_base',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Meta_Actual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Meta_2025',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Meta_2026',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Meta_2027',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Meta_Cuatrenio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Unidad_de_medida',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='Progreso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='MetaProducto',
        ),
    ]
