# Generated by Django 5.1 on 2024-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0019_remove_indicador_producto_linea_meta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_estrategica',
            name='ID',
        ),
        migrations.AddField(
            model_name='linea_estrategica',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
