# Generated by Django 5.1 on 2024-09-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0020_remove_linea_estrategica_id_linea_estrategica_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilar_sectorial',
            old_name='ID',
            new_name='CodigoP',
        ),
    ]
