# Generated by Django 5.1 on 2024-09-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0021_rename_id_pilar_sectorial_codigop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilar_sectorial',
            old_name='Nombre',
            new_name='Nombre_Pilar',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='Nombre',
            new_name='Nombre_Programa',
        ),
    ]
