# Generated by Django 5.1 on 2024-09-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0022_rename_nombre_pilar_sectorial_nombre_pilar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ID',
            new_name='ID_Producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='Nombre_Producto',
        ),
    ]
