# Generated by Django 5.1 on 2024-09-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0026_producto_soporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Soporte',
            new_name='soporte',
        ),
    ]
