# Generated by Django 5.1 on 2024-09-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0027_rename_soporte_producto_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
