# Generated by Django 5.1 on 2024-09-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0028_alter_producto_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='soporte',
        ),
    ]
