# Generated by Django 5.1 on 2024-09-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0029_remove_producto_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Meta_2025',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Meta_2026',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Meta_2027',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Meta_Cuatrenio',
        ),
    ]
