# Generated by Django 5.1 on 2024-10-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0030_remove_producto_meta_2025_remove_producto_meta_2026_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='soporte',
            field=models.FileField(null=True, upload_to='archivos/'),
        ),
    ]
