# Generated by Django 5.1 on 2024-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0031_producto_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='soporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
