# Generated by Django 5.1 on 2024-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0032_alter_producto_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Presupuesto_meta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Presupuesto_utilizado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='soporte',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
