# Generated by Django 5.1 on 2024-10-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0033_producto_presupuesto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presupuesto_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
