# Generated by Django 5.1 on 2024-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0034_producto_presupuesto_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_presupuesto_adicional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
