# Generated by Django 5.1 on 2024-10-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0035_producto_mostrar_presupuesto_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Linea_base',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Presupuesto_meta',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Presupuesto_utilizado',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
