# Generated by Django 5.1 on 2024-10-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0036_alter_producto_linea_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
