# Generated by Django 5.1 on 2024-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0037_alter_producto_presupuesto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ID_estado',
        ),
        migrations.RemoveField(
            model_name='historicoproducto',
            name='ID_estadoProducto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Linea_base',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Presupuesto_meta',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Presupuesto_utilizado',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True),
        ),
        migrations.DeleteModel(
            name='EstadoProducto',
        ),
    ]
