# Generated by Django 5.1 on 2024-10-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0038_remove_producto_id_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vigencia'),
        ),
    ]
