# Generated by Django 5.1 on 2024-10-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0039_producto_estado_producto_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
