# Generated by Django 5.1 on 2024-10-23 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0040_alter_producto_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
            options={
                'db_table': 'vigencia',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vigencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.vigencia'),
            preserve_default=False,
        ),
    ]
