# Generated by Django 5.1 on 2024-10-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0041_vigencia_alter_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
