# Generated by Django 5.1 on 2024-10-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0043_usuario_es_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_staff',
        ),
    ]
