# Generated by Django 5.1 on 2024-10-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0044_remove_usuario_es_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
