# Generated by Django 5.1 on 2024-10-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0045_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Prioridad',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='PrioridadProducto',
        ),
    ]
