# Generated by Django 5.1 on 2024-11-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0046_alter_producto_prioridad_delete_prioridadproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Prioridad',
        ),
    ]
