# Generated by Django 5.1 on 2024-11-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0048_producto_prioridad_producto_porcentaje_utilizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='porcentaje_utilizado',
        ),
    ]
