# Generated by Django 5.1 on 2024-11-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0049_remove_producto_porcentaje_utilizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
    ]
