# Generated by Django 5.1 on 2024-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0051_remove_producto_presupuesto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True),
        ),
    ]
