# Generated by Django 5.1 on 2024-11-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0052_alter_producto_presupuesto_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presupuesto_adicional',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=17),
            preserve_default=False,
        ),
    ]
