# Generated by Django 5.1 on 2024-11-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0053_alter_producto_presupuesto_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='mostrar_presupuesto_adicional',
        ),
        migrations.AddField(
            model_name='producto',
            name='mostrarPresupuestoAdicional',
            field=models.BooleanField(default=True),
        ),
    ]
