# Generated by Django 5.1 on 2024-11-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0054_remove_producto_mostrar_presupuesto_adicional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='mostrarPresupuestoAdicional',
            new_name='mostrar_presupuesto_adicional',
        ),
    ]
