# Generated by Django 5.1 on 2024-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0057_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Imagen',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
