# Generated by Django 5.1 on 2024-11-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0058_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Imagen',
        ),
    ]
