# Generated by Django 5.1 on 2024-11-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0059_remove_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Status_Meta',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
