# Generated by Django 5.1 on 2024-11-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0061_remove_historicoproducto_descripción_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ID_Producto',
        ),
        migrations.AddField(
            model_name='pilar_sectorial',
            name='Linea_estrategica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.linea_estrategica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='pilar_sectorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.pilar_sectorial'),
        ),
    ]
