# Generated by Django 5.1 on 2024-11-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0062_remove_producto_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Codigo_producto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
