# Generated by Django 5.1 on 2024-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0063_producto_codigo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cargo_usuario',
            },
        ),
    ]
