# Generated by Django 5.1 on 2024-11-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0064_cargo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Cargo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appSemaforo.cargo_usuario'),
            preserve_default=False,
        ),
    ]
