# Generated by Django 5.1 on 2024-11-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0065_usuario_cargo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo_usuario',
            name='ID',
        ),
    ]
