# Generated by Django 5.1 on 2024-11-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0066_remove_cargo_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo_usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='cargo_usuario',
            name='ID_cargo',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
