# Generated by Django 5.1 on 2024-11-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0068_alter_linea_estrategica_secretario_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea_estrategica',
            name='Secretario_Responsable',
        ),
    ]
