# Generated by Django 5.1 on 2024-11-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0070_producto_secretario_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador_producto',
            name='Codigo_indicador',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
