# Generated by Django 5.1 on 2024-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0072_remove_indicador_producto_id_indicador_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoproducto',
            name='Descripcion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
