# Generated by Django 5.1 on 2024-11-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0073_historicoproducto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_eliminacion',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
