# Generated by Django 5.1 on 2024-11-20 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0074_producto_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario_accion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioUltimaAccion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
