# Generated by Django 5.1 on 2024-11-20 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0075_producto_usuario_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='usuario_accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioUltimaAccion', to=settings.AUTH_USER_MODEL),
        ),
    ]
