# Generated by Django 5.1 on 2024-11-20 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0076_alter_producto_usuario_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoproducto',
            name='ID_Producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSemaforo.producto'),
        ),
        migrations.AlterField(
            model_name='historicoproducto',
            name='ID_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
