# Generated by Django 5.1 on 2024-11-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0077_alter_historicoproducto_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoproducto',
            name='Tipo_cambio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO'), ('Inhabilitado', 'INHABILITADO')], max_length=50),
        ),
    ]
