# Generated by Django 5.1 on 2024-11-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0078_historicoproducto_tipo_cambio_alter_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoproducto',
            name='ID',
        ),
        migrations.AddField(
            model_name='historicoproducto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
