# Generated by Django 5.1 on 2024-11-27 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0079_remove_historicoproducto_id_historicoproducto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Prioridad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario_accion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Codigo_producto',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_Indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.indicador_producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_LineaEstrategica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.linea_estrategica'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_Pilar_Sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.pilar_sectorial'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.programa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_usuarioAsignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario_asignado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_usuarioPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario_asignador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Secretario_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.cargo_usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Unidad_de_medida',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('HÉCTAREAS', 'Héctareas'), ('KILÓMETROS', 'Kilómetros'), ('METROS CUADRADOS', 'Metros Cuadrados'), ('METROS LINEALES', 'Metros Lineales'), ('MINUTOS', 'Minutos'), ('NÚMERO', 'Número')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vigencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.vigencia'),
        ),
    ]
