# Generated by Django 5.1 on 2024-11-27 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0081_remove_producto_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO'), ('Inhabilitado', 'INHABILITADO')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_usuarioAsignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AsignadoProducto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_usuarioPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AsignarProducto', to=settings.AUTH_USER_MODEL),
        ),
    ]
