# Generated by Django 5.1 on 2024-11-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0082_producto_prioridad_producto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilar_sectorial',
            name='Linea_estrategica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.linea_estrategica'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='pilar_sectorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appSemaforo.pilar_sectorial'),
        ),
    ]
