# Generated by Django 5.1 on 2024-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0083_alter_pilar_sectorial_linea_estrategica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='soporte_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
