# Generated by Django 5.1 on 2025-01-14 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0084_producto_soporte_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nueva_vigencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vigencia_reprogramada', to='appSemaforo.vigencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO'), ('Inhabilitado', 'INHABILITADO'), ('Expirada', 'EXPIRADA')], max_length=50),
        ),
    ]
