# Generated by Django 5.1 on 2025-01-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0087_producto_vigencia_anterior_alter_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('ID_Contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Numero_beneficiarios', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
    ]
