# Generated by Django 5.1 on 2025-01-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0088_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Contrato_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContratoUno', to='appSemaforo.contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Contrato_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContratoDos', to='appSemaforo.contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Contrato_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContratoTres', to='appSemaforo.contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Contrato_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContratoCuatro', to='appSemaforo.contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Contrato_5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ContratoCinco', to='appSemaforo.contrato'),
            preserve_default=False,
        ),
    ]
