# Generated by Django 5.1 on 2025-01-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0089_producto_contrato_1_producto_contrato_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Presupuesto_meta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Presupuesto_utilizado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='mostrar_presupuesto_adicional',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='presupuesto_adicional',
        ),
    ]
