# Generated by Django 5.1 on 2025-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0090_remove_producto_presupuesto_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
