# Generated by Django 5.1 on 2025-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0091_producto_presupuesto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Presupuesto_utilizado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
