# Generated by Django 5.1 on 2025-02-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSemaforo', '0092_producto_presupuesto_utilizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='Nombre',
            new_name='Duración',
        ),
        migrations.AddField(
            model_name='contrato',
            name='Objeto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
